# https://doc.rust-lang.org/cargo/getting-started/first-steps.html#first-steps-with-cargo
[package]
name = "none-shall-pass"
version = "0.0.2"
description = "GitHub Action to validate hyperlinks in all markdown files"
license = "MIT"

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
regex = "1.10.2"
glob = "0.3"
