# https://doc.rust-lang.org/cargo/getting-started/first-steps.html#first-steps-with-cargo
[package]
name = "none-shall-pass"
version = "0.0.4"
description = "GitHub Action to validate hyperlinks in all markdown files"
license = "MIT"
documentation = "https://thevickypedia.github.io/none-shall-pass-rustic"
homepage = "https://github.com/thevickypedia/none-shall-pass-rustic"
repository = "https://github.com/thevickypedia/none-shall-pass-rustic"

### For local debug purpose
#[[bin]]
#name = "none"
#path = "src/main.rs"

[dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
regex = "1.10.2"
glob = "0.3"
