name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Display Cargo Version
      run: |
        version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
        echo "Package Version: $version"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
