name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Release Flag
      # todo: Set release condition as flag
      run: |
        current_version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
        latest_version=$(curl -s https://crates.io/api/v1/crates/none-shall-pass | jq -r '.versions[0].num')
        echo "Cargo Package Version: ${current_version}"
        echo "Crate Package Version: ${latest_version}"
        if [ "$latest_version" != "$current_version" ]; then
          echo "Version has changed. Set release flag to true."
        else
          echo "Version has not changed. Set release flag to false."
        fi
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check Compiled Binary
      # todo: Check if binary is available
      run: |
        pwd
        ls -ltrh
